apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgtm-data
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
      - name: lgtm
        image: grafana/otel-lgtm:0.11.6
        ports:
        - containerPort: 3000  # Grafana
          name: grafana
        - containerPort: 3100  # Loki
          name: loki
        - containerPort: 9090  # Prometheus API
          name: prometheus
        - containerPort: 9009  # Mimir remote write
          name: mimir
        - containerPort: 3200  # Tempo
          name: tempo-http
        - containerPort: 4317  # OTLP gRPC
          name: otlp-grpc
        - containerPort: 4318  # OTLP HTTP
          name: otlp-http
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: traceqlEditor,traceToProfiles,profilesExplorer
        - name: GF_INSTALL_PLUGINS
          value: grafana-pyroscope-datasource
        volumeMounts:
        - name: data
          mountPath: /data
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lgtm-data
      - name: datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: observability
spec:
  selector:
    app: lgtm
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  - name: loki
    port: 3100
    targetPort: 3100
  - name: prometheus
    port: 9090
    targetPort: 9090
  - name: mimir
    port: 9009
    targetPort: 9009
  - name: tempo-http
    port: 3200
    targetPort: 3200
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318